spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.qvmhhmgsunkdkicaaobl
spring.datasource.password=VUfAVsZvNBVS4aJt
spring.jpa.hibernate.ddl-auto=create
spring.profiles.active=dev
jwt.secret=a2a1f8a7d6e5a4d3c2b1a0f9e8d7c6b5a4d3c2b1a0f9e8d7c6b5a4d3c2b1a0f9e8d7c6b5a4d3c2b1a0f9e8d7c6b5
jwt.expiration-ms=86400000
