spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.qvmhhmgsunkdkicaaobl
spring.datasource.password=VUfAVsZvNBVS4aJt
# 'create' apaga e recria o esquema do banco a cada inicialização.
# Ótimo para desenvolvimento quando o modelo de dados muda.
spring.jpa.hibernate.ddl-auto=create

# Ativa o perfil de desenvolvimento para carregar dados de teste
spring.profiles.active=dev

# Configurações do JWT
jwt.secret=a2a1f8a7d6e5a4d3c2b1a0f9e8d7c6b5a4d3c2b1a0f9e8d7c6b5a4d3c2b1a0f9e8d7c6b5a4d3c2b1a0f9e8d7c6b5
# Tempo de expiração do token em milissegundos (24 horas)
jwt.expiration-ms=86400000
