name: CI/CD Pipeline

on:
  push:
    branches: [ "apirestfull" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build com Maven
        run: mvn clean package -DskipTests

      - name: Build da imagem Docker
        run: docker build -t api-java .

      - name: Simulação de deploy
        run: echo "Deploy realizado com sucesso 🚀"
